name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-eslint:
    name: 'Lint: ESLint'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    with:
      script: lint:eslint

  lint-prettier:
    name: 'Lint: Prettier'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    with:
      script: lint:prettier

  lint-commits:
    name: 'Lint: Commits'
    uses: jrposada/github-actions/.github/workflows/conventional-commits.yml@v1

  test-unit:
    name: 'Test: Unit'
    uses: jrposada/github-actions/.github/workflows/npm-script.yml@v1
    with:
      script: coverage

  build:
    name: 'Build'
    uses: jrposada/github-actions/.github/workflows/tauri-build.yml@v1
    with:
      bundle-folder: ./src-tauri/target/release/bundle
      artifact-name: binary
      script: tauri build

  release:
    name: Release
    needs: [lint-eslint, lint-prettier, lint-commits, test-unit, build]
    uses: jrposada/github-actions/.github/workflows/semantic-release.yml@v1
